name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        ./do_install.sh
    - name: Test with pytest
      run: |
        python3 -m pytest -vrf
