name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      GAUNTLET_DIR: $GITHUB_WORKSPACE/../gauntlet
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        git clone https://github.com/p4gauntlet/gauntlet $GAUNTLET_DIR
        rm -rf $GAUNTLET_DIR/modules/pruner/*
        mv $GITHUB_WORKSPACE/* $GAUNTLET_DIR/modules/pruner
        cd $GAUNTLET_DIR
        ./do_install.sh
    - name: Test with pytest
      run: |
        python3 -m pytest test_pruner.py  -vrf
      working-directory: $GAUNTLET_DIR/modules/pruner
